## Pandas

In [2]:
import pandas as pd

In [3]:
info = {
    "Name" : ["Rahul", "Harshita", "Harsh"],
    "CGPA" : [9.5, 7.5, 4.4]
}

df = pd.DataFrame(info)

print(df)

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2     Harsh   4.4

In [4]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2     Harsh   4.4

In [5]:
# Series (1D labeld array)
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

# index
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

In [6]:
s = pd.Series([23, 24, 25, 26], index=["Adam", "Eve", "Bob", "Charlie"])
print(s)

print(s["Adam"])
print(s["Bob"])

print(s.index)

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
23
25
Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

In [7]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

print(s1 + s2)

s1[0] = 100
print(s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [8]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

print(s1 + s2)

s1[0] = 100
change_s1 = s1.drop(0)

print(s1)
(print(change_s1))

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
# DataFrame
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Age" : [23, 24, 25],
    "GPA" : [9.5, 8.6, 7.2]
}

df = pd.DataFrame(info)

print(df, type(df))

print(df.index)
print(df.columns)

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.6
2   Bob   25  7.2 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [10]:
df = pd.DataFrame([["Adam", 23], ["Bob", 24], ["Eve", 25]], columns=["Name", "Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   25

In [11]:
# Create DataFrame by NumPy Arrays
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(np_arr, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

### Usage with csv & json files

In [12]:
# CSV data
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [13]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [14]:
# json data
df = pd.read_json("employee_data.json")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [15]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

### DataFrame Methods
- df.head()
- df.tail()
- df.sample()
- df.info()
- df.shape()
- df.describe()
- df.columns
- df.nunique()

In [16]:
# CSV data
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [17]:
# Methods
print(df.head()) # Starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [18]:
# Methods
df.head() # Starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [19]:
# Methods
df.head() # Starting 5 rows
df.tail() # Last 5 rows

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [20]:
# Methods
df.head() # Starting 5 rows
df.tail(2) # Last 5 rows

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [21]:
# Methods
df.head() # Starting 5 rows
df.tail() # Last 5 rows
df.sample() #Ramdom sample value

   ID   Name  Age Department  Salary
5   6  Frank   29    Finance   50000

In [22]:
# Methods
df.head(10) # Starting 10 rows
df.tail(2) # Last 2 rows
df.sample(5) # 5 Ramdom sample value

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
5   6  Frank   29    Finance   50000
1   2    Bob   32         IT   72000
6   7  Grace   41         HR   82000
3   4  David   45  Marketing   91000

In [23]:
# Methods
df.head(10) # Starting 10 rows
df.tail(2) # Last 2 rows
df.sample(5) # 5 Ramdom sample value

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [24]:
# Methods
df.head(10) # Starting 10 rows
df.tail(2) # Last 2 rows
df.sample(5) # 5 Ramdom sample value

df.info()

df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

(10, 5)

In [25]:
# # Methods
# df.head(10) # Starting 10 rows
# df.tail(2) # Last 2 rows
# df.sample(5) # 5 Ramdom sample value

# df.info()

# df.shape

df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [26]:
# # Methods
# df.head(10) # Starting 10 rows
# df.tail(2) # Last 2 rows
# df.sample(5) # 5 Ramdom sample value

# df.info()

# df.shape

# df.describe()

df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [27]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [28]:
# AQI Data se
df = pd.read_csv("globalAirQuality.csv")
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [29]:
# AQI Data se
df = pd.read_csv("globalAirQuality.csv")
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [30]:
# AQI Data se
df = pd.read_csv("globalAirQuality.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

### Selecting Data
- Select Columns
- Select Rows (Label & Index based) - loc & iloc
- Select Rows & Columns
- Select single scalar values - at & iat

In [31]:
# Selecting data
df["city"]
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [32]:
# Selecting data
df["city"]
df[["city", "aqi"]]

df.loc[2]

timestamp      2025-11-04 20:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                                42.25
pm10                               82.553
no2                                26.935
so2                                 9.538
o3                                  23.32
co                                  0.977
aqi                                    84
temperature                        31.833
humidity                           62.783
wind_speed                           9.65
Name: 2, dtype: object

In [33]:
# Selecting data
df["city"]
df[["city", "aqi"]]

df.loc[0:2] # Starting idx : end idx (inclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [34]:
# Selecting data
df["city"]
df[["city", "aqi"]]

df.iloc[0:3] # Starting idx : end idx (exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [35]:
# cells - row, col
df.loc[0:2, ["city", "aqi"]]
df.columns

df.iloc[0:3, 2]

0    New York
1    New York
2    New York
Name: city, dtype: object

In [36]:
# cells - row, col
df.loc[0:2, ["city", "aqi"]]
df.columns

# df.iloc[0:3, 2]
df.loc[0:2, ["country","city", "latitude", "longitude"]]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [37]:
# cells - row, col
df.loc[0:2, ["city", "aqi"]]
df.columns

# df.iloc[0:3, 2]
df.loc[0:2, ["country","city", "latitude", "longitude"]]
df.iloc[0:3, 1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [38]:
# cells - row, col
df.loc[0:2, ["city", "aqi"]]
df.columns

# df.iloc[0:3, 2]
df.loc[0:2, ["country","city", "latitude", "longitude"]]
df.iloc[0:3, 1:5]

# cell
df.at[0, "city"]
df.iat[0, 2]

'New York'

In [39]:
cities = df["city"].copy()
cities[0] = "Mumbai" # copy

cities

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

### Filtering Data

In [40]:
# Filtering of Data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [41]:
# Filtering of Data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]
df[ (df["aqi"] > 100) & (df["temperature"] < 30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
12,2025-11-05 06:25:17.554219,US,New York,40.713,-74.006,57.227,28.916,30.698,8.091,63.108,0.967,114,14.584,46.654,5.570
13,2025-11-05 07:25:17.554219,US,New York,40.713,-74.006,26.147,58.714,49.826,5.228,51.651,0.615,124,27.299,76.014,0.786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17988,2025-11-19 06:25:17.554219,CH,Zurich,47.377,8.542,61.305,97.044,23.317,6.793,57.102,1.022,122,13.982,30.822,6.769
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [42]:
# Filtering of Data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]
df[ (df["aqi"] > 100) & (df["temperature"] < 30)]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]

aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

### query() rules
- Expression as a string
- Column based reference
- Backticks for col_name with space or special chars
- Operators (&, |,~,>=,>,<=,<,== etc,)
- @ to referance Python vars
- Chained comparison

In [43]:
# Filtering of Data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]
df[ (df["aqi"] > 100) & (df["temperature"] < 30)]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]

aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

# Query
df.query("aqi > 100")
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [44]:
# Filtering of Data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]
df[ (df["aqi"] > 100) & (df["temperature"] < 30)]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]

aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

# Query
aqi_val = 100
df.query("aqi > 100")
df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [45]:
# Filtering of Data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]
df[ (df["aqi"] > 100) & (df["temperature"] < 30)]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]

aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

# Query - copy
aqi_val = 100
df.query("aqi > 100")
aqi_data = df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]].copy()

In [46]:
aqi_data

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [47]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

### Cleaning Data

1. Handle Missing Values
- isnull() / isna()
- isnull().sum()
- dropna()
- fillna()
- fill()
- bfill()

In [48]:
# Cleaning Data - missing values

df = pd.read_csv("raw_data.csv")

df.isnull()
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [49]:
# Cleaning Data - missing values
df = pd.read_csv("raw_data.csv")

df.isnull()

df.isnull().sum()

df.dropna() # row drop
df.dropna(axis=1) # col drop

df.fillna(0)
df.fillna(100)

    id          name    age country   gender   income
0    1      John Doe   29.0     USA     Male  55000.0
1    1      John Doe   29.0     USA     Male  55000.0
2    2    Jane Smith  100.0  Canada   Female  62000.0
3    3          Alex  100.0     USA  Unknown  47000.0
4    4  Maria Garcia   34.0   Spain   Female    100.0
5    5        Li Wei   27.0   China     Male  51000.0
6    6           100   45.0   India   Female  73000.0
7    7    Ahmed Khan   38.0     100     Male  68000.0
8    8    Rachel Lee   29.0     USA   Female  62000.0
9    9   Carlos Ruiz  100.0  Mexico     Male  45000.0
10  10   Emily Davis   31.0     USA      100  58000.0

In [50]:
# Cleaning Data - missing values
df = pd.read_csv("raw_data.csv")

df.isnull()

df.isnull().sum()

df.dropna() # row drop
df.dropna(axis=1) # col drop

df.fillna(0)

df["age"].fillna(0)

0     29.0
1     29.0
2      0.0
3      0.0
4     34.0
5     27.0
6     45.0
7     38.0
8     29.0
9      0.0
10    31.0
Name: age, dtype: float64

In [51]:
# Cleaning Data - missing values
df = pd.read_csv("raw_data.csv")

df.isnull()

df.isnull().sum()

df.dropna() # row drop
df.dropna(axis=1) # col drop

df.fillna(0)

age_mean = df["age"].mean()
df["age"].fillna(age_mean)

0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [52]:
# Cleaning Data - missing values
df = pd.read_csv("raw_data.csv")

df.isnull()

df.isnull().sum()

df.dropna() # row drop
df.dropna(axis=1) # col drop

df.fillna(0)

age_mean = df["age"].mean()

cleand_data = df.copy()
age_mean = cleand_data["age"].mean()
cleand_data["age"] = cleand_data["age"].fillna(age_mean)

cleand_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [53]:
# Cleaning Data - missing values
df = pd.read_csv("raw_data.csv")

df.isnull()

df.isnull().sum()

df.dropna() # row drop
df.dropna(axis=1) # col drop

df.fillna(0)

age_mean = df["age"].mean()

cleand_data = df.copy()
age_mean = cleand_data["age"].mean()
cleand_data["age"] = cleand_data["age"].fillna(age_mean)

df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [54]:
# Cleaning Data - missing values
df = pd.read_csv("raw_data.csv")

df.isnull()

df.isnull().sum()

df.dropna() # row drop
df.dropna(axis=1) # col drop

df.fillna(0)

age_mean = df["age"].mean()

cleand_data = df.copy()
age_mean = cleand_data["age"].mean()
cleand_data["age"] = cleand_data["age"].fillna(age_mean)

df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Cleaning Data
1. Handle Duplicate Values
- duplicated()
- drop_duplicates()

In [55]:
# Handle Duplicates

df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [56]:
# Handle Duplicates

df["country"].duplicated() #Duplicate cheack for country

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [57]:
# Handle Duplicates

df[["country", "gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [58]:
# Handle Duplicates

df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [59]:
# Handle Duplicates
df[["country", "gender"]].duplicated() 
df2 = df.copy()
df.drop_duplicates(inplace=True)

### Claning Data
1. Handle Data Types & date-time
- dtypes
- astype( newType )
- to_datetime()

In [60]:
# Data Types

df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [ ]:
# Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [62]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [66]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"].dtypes

dtype('O')

In [68]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])

aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [64]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

### Cleaning Data
1. Handle String
- .str.lower(),.str.upper()&.capitalize()
- .str.strip()
- .str.split(" ")
- .str.contains(val, case=False)

In [ ]:
# Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

df["gender"].str.lower()

0        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object

In [73]:
# Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

df["gender"].str.upper()

0        MALE
2      FEMALE
3     UNKNOWN
4      FEMALE
5        MALE
6      FEMALE
7        MALE
8      FEMALE
9        MALE
10        NaN
Name: gender, dtype: object

In [74]:
# Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

df["gender"].str.capitalize()

0        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [75]:
# Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

df["gender"].str.upper()

df["name"].str.split(" ")

0         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [76]:
# Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

df["gender"].str.upper()

df["name"].str.split(" ")

df["country"].str.contains("US")

0      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

In [77]:
# Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

df["gender"].str.upper()

df["name"].str.split(" ")

df["country"].str.contains("India")

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [78]:
# Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

df["gender"].str.upper()

df["name"].str.split(" ")

df["country"].str.contains("India", case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [70]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0